image: node:14-buster

before_script:
  - npm install

stages:
  - publish

publish-job:
  stage: publish
  script:
    - |
      apt update
      apt install -y libasound2 libgbm1 libgtk-3-0 libnss3 xvfb
      xvfb-run -a npm run test
      npm run package
      npm run publish